
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HARSH
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    DisplayManager disp;
    public Booking(DisplayManager disp) {
        this.disp = disp; 
        initComponents();
    }
    public Booking() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonlabel1 = new javax.swing.JLabel();
        buttonlabel2 = new javax.swing.JLabel();
        buttonlabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Spartans - Booking Screen");
        setPreferredSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(null);

        buttonlabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlabel1MouseClicked(evt);
            }
        });
        getContentPane().add(buttonlabel1);
        buttonlabel1.setBounds(430, 495, 130, 35);

        buttonlabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonlabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlabel2MouseClicked(evt);
            }
        });
        getContentPane().add(buttonlabel2);
        buttonlabel2.setBounds(290, 540, 90, 40);

        buttonlabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonlabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlabel3MouseClicked(evt);
            }
        });
        getContentPane().add(buttonlabel3);
        buttonlabel3.setBounds(612, 540, 80, 30);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 100, 90, 30);

        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(450, 100, 170, 30);

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel3.setText("NUMBER OF SEATS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 330, 170, 17);

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel5.setText("* TERMS & CONDITIONS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 390, 210, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jRadioButton1.setText("AGREE");
        jRadioButton1.setBorder(null);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(450, 380, 130, 50);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jRadioButton2.setText("DISAGREE");
        jRadioButton2.setBorder(null);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(560, 380, 130, 50);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 170, 140, 30);

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(370, 210, 140, 30);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(370, 250, 150, 30);

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(370, 290, 150, 30);

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel20);
        jLabel20.setBounds(370, 327, 140, 40);

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(730, 170, 140, 30);

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(730, 210, 150, 30);

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel23);
        jLabel23.setBounds(730, 250, 110, 40);

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel24);
        jLabel24.setBounds(730, 290, 110, 40);

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel6.setText("SOURCE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 210, 80, 30);

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel7.setText("DESTINATION");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 250, 103, 17);

        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel8.setText("DEPARTURE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 290, 91, 17);

        jLabel9.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel9.setText("ARRIVAL");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 330, 66, 17);

        jLabel10.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel10.setText("FLIGHT ID");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 170, 80, 30);

        jLabel11.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel11.setText("CONNECTING FLIGHT");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 170, 162, 17);

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel12.setText("FROM");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 210, 44, 17);

        jLabel13.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel13.setText("TRANSIT TIME");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(530, 250, 107, 17);

        jLabel14.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel14.setText("TOTAL FLIGHT TIME");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 290, 153, 17);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(730, 330, 70, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen 3.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 1000, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buttonlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlabel1MouseClicked
         if(jTextField1.getText().trim().length()>0 && jTextField1.getText().matches("^[ A-z]+$") && jRadioButton1.isSelected()==true){
            buttonlabel1.setEnabled(true);
            int PNR = disp.frs.dataManager.getPNR();
            disp.confirm.jLabel6.setText(String.valueOf(PNR));
            disp.confirm.jLabel7.setText(disp.booking.jTextField1.getText());
            disp.confirm.jLabel10.setText("CONFIRMED");
            disp.confirm.jLabel9.setText(disp.Inp.cls);
            disp.confirm.jLabel12.setText(disp.Inp.seats.toString());
            disp.confirm.jLabel11.setText(disp.Inp.s.toString());
            disp.frs.bookingManager.bookTicket(disp.frs.FlightSegment.get(disp.results.Index), disp.booking.jTextField1.getText(),PNR,disp.Inp.seats);
            disp.showConfirmationScreen();            
        } else if(jTextField1.getText().matches("^[ A-z]+$")==false) {
            JOptionPane.showMessageDialog(new JFrame(),"Fill your Name correctly");
        } else if(jTextField1.getText().trim().length()>0) {
            JOptionPane.showMessageDialog(new JFrame(),"Accept Terms & Condition!");
        } else {
            JOptionPane.showMessageDialog(new JFrame(),"Fill Your Name");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonlabel1MouseClicked

    private void buttonlabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlabel2MouseClicked
        disp.booking.setVisible(false);
        disp.results.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonlabel2MouseClicked

    private void buttonlabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonlabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel buttonlabel1;
    private javax.swing.JLabel buttonlabel2;
    private javax.swing.JLabel buttonlabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    void jTextArea1(String source_s, String source) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void jTextArea1(String source) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
