/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HARSH
 */
public class Confirmation extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation
     */
    DisplayManager disp;
    public Confirmation(DisplayManager disp) {
        this.disp = disp; 
        initComponents();
    }
        
    public Confirmation() {
        initComponents();
        this.setSize(1000,650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonlabel1 = new javax.swing.JLabel();
        buttonlabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bglabe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spartans - Confirmation Screen");
        setPreferredSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("REFERENCE NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 210, 211, 22);

        buttonlabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlabel1MouseClicked(evt);
            }
        });
        getContentPane().add(buttonlabel1);
        buttonlabel1.setBounds(440, 570, 120, 30);

        buttonlabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonlabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlabel2MouseClicked(evt);
            }
        });
        getContentPane().add(buttonlabel2);
        buttonlabel2.setBounds(600, 570, 70, 30);

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("SEAT STATUS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 290, 137, 22);

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 250, 59, 22);

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 210, 250, 30);

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 250, 240, 30);

        jLabel10.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 290, 210, 30);

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("DATE OF TRAVEL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 410, 170, 22);

        jLabel11.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(250, 412, 200, 30);

        jLabel9.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 370, 210, 30);

        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel8.setText("NO. OF SEATS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 327, 150, 22);

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 330, 190, 30);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("CLASS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 360, 170, 30);

        bglabe.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bglabe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen 4.jpg"))); // NOI18N
        getContentPane().add(bglabe);
        bglabe.setBounds(0, 0, 1010, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlabel1MouseClicked
        disp.confirm.setVisible(false);
        disp.frs.initializeOthers(disp.frs);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonlabel1MouseClicked

    private void buttonlabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlabel2MouseClicked
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonlabel2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bglabe;
    private javax.swing.JLabel buttonlabel1;
    private javax.swing.JLabel buttonlabel2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
